language: python
python:
    - "2.7"
    - "2.6"

branches:
    only:
        - master

sudo: false

install:
    - if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then SPHINX_VERSION=1.4.9; fi
    - pip install sphinx${SPHINX_VERSION:+==$SPHINX_VERSION}
    - pip install -r requirements-travis.txt

script:
    - inspekt indent
    - inspekt lint
    - inspekt style
