language: python
python:
    - "2.7"

branches:
    only:
        - master

sudo: false

install:
    - pip install Sphinx
    - pip install -r requirements-travis.txt

script:
    - inspekt indent
    - inspekt lint
    - inspekt style
